apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-service
  description: Sample service owned by Team X
  tags:
    - microservice
spec:
  type: service
  lifecycle: production
  owner: team-x
